### ISSUE TITLE
Add LICENSE file

### ISSUE THREAD

**Issue by Remiii** [Exercise/GoogleTranslateBundle#9]
Add License file... Following the `composer.json` and Packagist the License are MIT.

![capture d ecran 2015-05-07 a 19 31 25](https://cloud.githubusercontent.com/assets/659383/7521644/d8545ca6-f4ef-11e4-8769-6db0faa5e9b5.png)

**Comment by spolischook** [comment]
Yea, you are right!

**Comment by spolischook** [comment]
fixed in https://github.com/Exercise/GoogleTranslateBundle/pull/10
